version = 1
SPDX-PackageName = "tree-sitter-build2"
SPDX-PackageSupplier = "Will Reed <wreed@disroot.org>"

[[annotations]]
SPDX-FileCopyrightText = "2026 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "LGPL-3.0-or-later WITH LGPL-3.0-linking-exception"
path = [
    "src/**",
    "misc/**",
    "bindings/**",
    "examples/**",
    "queries/**",
    ".editorconfig",
    ".gitignore",
    ".gitattributes",
    ".version",
    "*.rst",
    "*.md",
    "*.txt",
    "*.mod",
    "*.toml",
    "*.py",
    "*.json",
    "*.swift",
    "*.gyp",
    "*.toml",
    "*.lock",
    "*.js",
    "*.zig*",
    "Makefile",
    "justfile"
]
