/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__line_continuation = 1,
  sym_path = 2,
  sym_name = 3,
  anon_sym_DASH = 4,
  anon_sym_PLUS = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_SPACE = 8,
  anon_sym_LBRACK = 9,
  anon_sym_EQ = 10,
  anon_sym_RBRACK = 11,
  anon_sym_COLON = 12,
  anon_sym_STAR = 13,
  anon_sym_PLUS_EQ = 14,
  anon_sym_DASH_EQ = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_quoted_string_token1 = 17,
  anon_sym_SQUOTE = 18,
  aux_sym_quoted_string_token2 = 19,
  aux_sym_string_token1 = 20,
  anon_sym_define = 21,
  anon_sym_using = 22,
  anon_sym_include = 23,
  anon_sym_info = 24,
  sym_document = 25,
  sym__prefix = 26,
  sym_single_target = 27,
  sym_multi_target = 28,
  sym_subject = 29,
  sym_target_attribute = 30,
  sym_dependency = 31,
  sym_glob = 32,
  sym_assigner = 33,
  sym_value = 34,
  sym_quoted_string = 35,
  sym_string = 36,
  sym_assignment = 37,
  sym_keyword = 38,
  sym_directive = 39,
  sym_path_target = 40,
  aux_sym_document_repeat1 = 41,
  aux_sym_subject_repeat1 = 42,
  aux_sym_subject_repeat2 = 43,
  aux_sym_subject_repeat3 = 44,
  aux_sym_dependency_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__line_continuation] = "_line_continuation",
  [sym_path] = "path",
  [sym_name] = "name",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SPACE] = " ",
  [anon_sym_LBRACK] = "[",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_string_token2] = "quoted_string_token2",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_define] = "define",
  [anon_sym_using] = "using",
  [anon_sym_include] = "include",
  [anon_sym_info] = "info",
  [sym_document] = "document",
  [sym__prefix] = "_prefix",
  [sym_single_target] = "single_target",
  [sym_multi_target] = "multi_target",
  [sym_subject] = "subject",
  [sym_target_attribute] = "target_attribute",
  [sym_dependency] = "dependency",
  [sym_glob] = "glob",
  [sym_assigner] = "assigner",
  [sym_value] = "value",
  [sym_quoted_string] = "quoted_string",
  [sym_string] = "string",
  [sym_assignment] = "assignment",
  [sym_keyword] = "keyword",
  [sym_directive] = "directive",
  [sym_path_target] = "path_target",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_subject_repeat1] = "subject_repeat1",
  [aux_sym_subject_repeat2] = "subject_repeat2",
  [aux_sym_subject_repeat3] = "subject_repeat3",
  [aux_sym_dependency_repeat1] = "dependency_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__line_continuation] = sym__line_continuation,
  [sym_path] = sym_path,
  [sym_name] = sym_name,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_string_token2] = aux_sym_quoted_string_token2,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_info] = anon_sym_info,
  [sym_document] = sym_document,
  [sym__prefix] = sym__prefix,
  [sym_single_target] = sym_single_target,
  [sym_multi_target] = sym_multi_target,
  [sym_subject] = sym_subject,
  [sym_target_attribute] = sym_target_attribute,
  [sym_dependency] = sym_dependency,
  [sym_glob] = sym_glob,
  [sym_assigner] = sym_assigner,
  [sym_value] = sym_value,
  [sym_quoted_string] = sym_quoted_string,
  [sym_string] = sym_string,
  [sym_assignment] = sym_assignment,
  [sym_keyword] = sym_keyword,
  [sym_directive] = sym_directive,
  [sym_path_target] = sym_path_target,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_subject_repeat1] = aux_sym_subject_repeat1,
  [aux_sym_subject_repeat2] = aux_sym_subject_repeat2,
  [aux_sym_subject_repeat3] = aux_sym_subject_repeat3,
  [aux_sym_dependency_repeat1] = aux_sym_dependency_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__line_continuation] = {
    .visible = false,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix] = {
    .visible = false,
    .named = true,
  },
  [sym_single_target] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_target] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_target_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_glob] = {
    .visible = true,
    .named = true,
  },
  [sym_assigner] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_path_target] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dependency_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_lhs = 2,
  field_rhs = 3,
  field_value = 4,
  field_variable = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_lhs] = "lhs",
  [field_rhs] = "rhs",
  [field_value] = "value",
  [field_variable] = "variable",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_variable, 0},
  [1] =
    {field_lhs, 0},
    {field_rhs, 2},
  [3] =
    {field_key, 1},
    {field_value, 3},
  [5] =
    {field_lhs, 1},
    {field_rhs, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
};

static const TSCharacterRange aux_sym_string_token1_character_set_2[] = {
  {0, '\t'}, {0x0b, '\f'}, {0x0e, '!'}, {'#', '&'}, {'(', ':'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 60,
        '\'', 64,
        '*', 57,
        '+', 47,
        '-', 44,
        '.', 14,
        ':', 56,
        '=', 54,
        '[', 53,
        '\\', 2,
        ']', 55,
        'd', 27,
        'i', 35,
        'u', 39,
        '{', 48,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(51);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '=') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '{') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(52);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(68);
      if (lookahead == '}') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      if (lookahead != 0 &&
          (lookahead < ':' || '=' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{') ADVANCE(71);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(52);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '=') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '}') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '.') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '0' || '=' < lookahead) &&
          (lookahead < 'A' || ']' < lookahead) &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(71);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < ':' || '=' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(71);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(61);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(65);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(67);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '{') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '{') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '=') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '=') ADVANCE(59);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '/') ADVANCE(24);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 18:
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 19:
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 20:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        ' ', 50,
        '+', 17,
        '-', 15,
        '.', 14,
        ':', 56,
        '=', 54,
        '[', 53,
        '\\', 2,
        'd', 27,
        'i', 35,
        'u', 39,
        '{', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 60,
        '\'', 64,
        '*', 57,
        '+', 17,
        '-', 15,
        '.', 14,
        ':', 56,
        '=', 54,
        '[', 53,
        '\\', 2,
        ']', 55,
        'd', 27,
        'i', 35,
        'u', 39,
        '{', 48,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__line_continuation);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_path);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'c') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(38);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'd') ADVANCE(29);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'e') ADVANCE(30);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'e') ADVANCE(72);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'e') ADVANCE(74);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(33);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'g') ADVANCE(73);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(36);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(37);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(40);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(25);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(31);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(28);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(75);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 's') ADVANCE(32);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == 'u') ADVANCE(26);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '=') ADVANCE(59);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '/') ADVANCE(24);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(50);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(35);
      if (lookahead == 'u') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(51);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ';') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '\\') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != ';') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ';') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != ';') ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '\\') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != ';') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != ';') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_2, 10, lookahead))) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == '/') ADVANCE(24);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_2, 10, lookahead))) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(24);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_2, 10, lookahead))) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_2, 10, lookahead))) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_define);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_using);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_include);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_info);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 20},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 20},
  [13] = {.lex_state = 20},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 10},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 12},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 12},
  [92] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__line_continuation] = ACTIONS(3),
    [sym_path] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(84),
    [sym_single_target] = STATE(6),
    [sym_multi_target] = STATE(6),
    [sym_target_attribute] = STATE(45),
    [sym_dependency] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_keyword] = STATE(92),
    [sym_directive] = STATE(2),
    [sym_path_target] = STATE(6),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__line_continuation] = ACTIONS(3),
    [sym_path] = ACTIONS(7),
    [sym_name] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_define] = ACTIONS(15),
    [anon_sym_using] = ACTIONS(15),
    [anon_sym_include] = ACTIONS(15),
    [anon_sym_info] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(7), 1,
      sym_path,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      sym_target_attribute,
    STATE(92), 1,
      sym_keyword,
    STATE(6), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
    ACTIONS(15), 4,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
    STATE(3), 4,
      sym_dependency,
      sym_assignment,
      sym_directive,
      aux_sym_document_repeat1,
  [42] = 11,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_path,
    ACTIONS(24), 1,
      sym_name,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    STATE(45), 1,
      sym_target_attribute,
    STATE(92), 1,
      sym_keyword,
    STATE(6), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
    ACTIONS(33), 4,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
    STATE(3), 4,
      sym_dependency,
      sym_assignment,
      sym_directive,
      aux_sym_document_repeat1,
  [84] = 9,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(42), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_SPACE,
    ACTIONS(49), 1,
      anon_sym_COLON,
    STATE(8), 1,
      aux_sym_dependency_repeat1,
    STATE(38), 1,
      sym_assigner,
    ACTIONS(47), 3,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
    ACTIONS(40), 7,
      sym_path,
      sym_name,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [120] = 7,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(58), 1,
      anon_sym_SPACE,
    STATE(38), 1,
      sym_assigner,
    ACTIONS(47), 3,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
    ACTIONS(53), 8,
      sym_path,
      sym_name,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [151] = 6,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(49), 1,
      anon_sym_COLON,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    STATE(8), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(40), 8,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [177] = 7,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(49), 1,
      anon_sym_COLON,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(40), 7,
      sym_path,
      sym_name,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [205] = 5,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(61), 2,
      anon_sym_SPACE,
      anon_sym_COLON,
    ACTIONS(68), 8,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [229] = 7,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      anon_sym_COLON,
    STATE(13), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(68), 7,
      sym_path,
      sym_name,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [257] = 6,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_COLON,
    STATE(13), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(68), 8,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [283] = 7,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_COLON,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(68), 7,
      sym_path,
      sym_name,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [311] = 5,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(78), 2,
      anon_sym_SPACE,
      anon_sym_COLON,
    ACTIONS(53), 8,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [335] = 5,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_dependency_repeat1,
    ACTIONS(61), 2,
      anon_sym_SPACE,
      anon_sym_COLON,
    ACTIONS(83), 8,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [359] = 8,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(85), 1,
      sym_path,
    ACTIONS(87), 1,
      sym_name,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      anon_sym_SPACE,
    STATE(37), 1,
      sym_assigner,
    ACTIONS(47), 3,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
    STATE(16), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
  [388] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 9,
      sym_path,
      sym_name,
      anon_sym_SPACE,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [409] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 10,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_SPACE,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [428] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 10,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_SPACE,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [447] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 10,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_SPACE,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [466] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 9,
      sym_path,
      sym_name,
      anon_sym_SPACE,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [487] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 10,
      sym_path,
      sym_name,
      anon_sym_LBRACE,
      anon_sym_SPACE,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [506] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(110), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [523] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(114), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [540] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(118), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [557] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(83), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [574] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(122), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [591] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(126), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [608] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(128), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(130), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [625] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(134), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [642] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(138), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [659] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(142), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [676] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(144), 4,
      ts_builtin_sym_end,
      sym_path,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(146), 5,
      sym_name,
      anon_sym_define,
      anon_sym_using,
      anon_sym_include,
      anon_sym_info,
  [693] = 9,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(148), 1,
      sym_path,
    ACTIONS(150), 1,
      sym_name,
    ACTIONS(152), 1,
      anon_sym_DASH,
    ACTIONS(154), 1,
      anon_sym_PLUS,
    ACTIONS(156), 1,
      anon_sym_STAR,
    STATE(55), 1,
      sym_glob,
    STATE(71), 1,
      sym__prefix,
    STATE(88), 1,
      sym_subject,
  [721] = 9,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(148), 1,
      sym_path,
    ACTIONS(150), 1,
      sym_name,
    ACTIONS(152), 1,
      anon_sym_DASH,
    ACTIONS(154), 1,
      anon_sym_PLUS,
    ACTIONS(156), 1,
      anon_sym_STAR,
    STATE(55), 1,
      sym_glob,
    STATE(71), 1,
      sym__prefix,
    STATE(89), 1,
      sym_subject,
  [749] = 9,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(148), 1,
      sym_path,
    ACTIONS(150), 1,
      sym_name,
    ACTIONS(152), 1,
      anon_sym_DASH,
    ACTIONS(154), 1,
      anon_sym_PLUS,
    ACTIONS(156), 1,
      anon_sym_STAR,
    STATE(55), 1,
      sym_glob,
    STATE(71), 1,
      sym__prefix,
    STATE(87), 1,
      sym_subject,
  [777] = 9,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(148), 1,
      sym_path,
    ACTIONS(150), 1,
      sym_name,
    ACTIONS(152), 1,
      anon_sym_DASH,
    ACTIONS(154), 1,
      anon_sym_PLUS,
    ACTIONS(156), 1,
      anon_sym_STAR,
    STATE(55), 1,
      sym_glob,
    STATE(71), 1,
      sym__prefix,
    STATE(83), 1,
      sym_subject,
  [805] = 6,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      sym_path,
    ACTIONS(160), 1,
      sym_name,
    STATE(29), 1,
      sym_assignment,
    STATE(16), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
  [826] = 8,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(162), 1,
      anon_sym_SPACE,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      anon_sym_SQUOTE,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    STATE(21), 1,
      sym_value,
    STATE(23), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
  [851] = 8,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      anon_sym_SQUOTE,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(170), 1,
      anon_sym_SPACE,
    STATE(22), 1,
      sym_value,
    STATE(23), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
  [876] = 6,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      sym_path,
    ACTIONS(160), 1,
      sym_name,
    STATE(24), 1,
      sym_assignment,
    STATE(16), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
  [897] = 8,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      anon_sym_SQUOTE,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(172), 1,
      anon_sym_SPACE,
    STATE(23), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
    STATE(30), 1,
      sym_value,
  [922] = 7,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      anon_sym_SQUOTE,
    STATE(21), 1,
      sym_value,
    STATE(23), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
  [944] = 5,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      sym_name,
    ACTIONS(158), 1,
      sym_path,
    STATE(16), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
  [962] = 7,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      anon_sym_SQUOTE,
    STATE(23), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
    STATE(30), 1,
      sym_value,
  [984] = 7,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      anon_sym_SQUOTE,
    ACTIONS(178), 1,
      sym_path,
    STATE(23), 1,
      sym_quoted_string,
    STATE(26), 1,
      sym_string,
  [1006] = 5,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(180), 1,
      sym_path,
    ACTIONS(182), 1,
      sym_name,
    STATE(10), 3,
      sym_single_target,
      sym_multi_target,
      sym_path_target,
  [1024] = 7,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      anon_sym_SQUOTE,
    STATE(23), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
    STATE(31), 1,
      sym_value,
  [1046] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(184), 1,
      anon_sym_SPACE,
    STATE(37), 1,
      sym_assigner,
    ACTIONS(47), 3,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
  [1061] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    STATE(40), 1,
      sym_assigner,
    ACTIONS(186), 3,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
  [1073] = 5,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(188), 1,
      sym_path,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      anon_sym_PLUS,
    STATE(79), 1,
      sym__prefix,
  [1089] = 4,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(194), 1,
      sym_name,
    STATE(82), 1,
      sym__prefix,
    ACTIONS(196), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1103] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(198), 1,
      anon_sym_SPACE,
    ACTIONS(200), 3,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      aux_sym_string_token1,
  [1115] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 1,
      anon_sym_SPACE,
    STATE(52), 1,
      aux_sym_subject_repeat3,
  [1128] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      anon_sym_SPACE,
    STATE(59), 1,
      aux_sym_subject_repeat1,
  [1141] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(211), 1,
      anon_sym_SPACE,
    STATE(52), 1,
      aux_sym_subject_repeat3,
  [1154] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(211), 1,
      anon_sym_SPACE,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_subject_repeat3,
  [1167] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    ACTIONS(217), 1,
      anon_sym_SPACE,
    STATE(56), 1,
      aux_sym_subject_repeat2,
  [1180] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    ACTIONS(222), 1,
      anon_sym_SPACE,
    STATE(57), 1,
      aux_sym_subject_repeat1,
  [1193] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    ACTIONS(227), 1,
      anon_sym_SPACE,
    STATE(56), 1,
      aux_sym_subject_repeat2,
  [1206] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(209), 1,
      anon_sym_SPACE,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_subject_repeat1,
  [1219] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    ACTIONS(227), 1,
      anon_sym_SPACE,
    STATE(62), 1,
      aux_sym_subject_repeat2,
  [1232] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(209), 1,
      anon_sym_SPACE,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_subject_repeat1,
  [1245] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(227), 1,
      anon_sym_SPACE,
    STATE(56), 1,
      aux_sym_subject_repeat2,
  [1258] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    ACTIONS(231), 1,
      anon_sym_SPACE,
    ACTIONS(233), 1,
      anon_sym_STAR,
  [1271] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(237), 1,
      sym_name,
    ACTIONS(235), 2,
      sym_path,
      anon_sym_LBRACE,
  [1282] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      anon_sym_SPACE,
    STATE(57), 1,
      aux_sym_subject_repeat1,
  [1295] = 4,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(227), 1,
      anon_sym_SPACE,
    STATE(58), 1,
      aux_sym_subject_repeat2,
  [1308] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(239), 1,
      anon_sym_DQUOTE,
    ACTIONS(241), 1,
      aux_sym_quoted_string_token1,
  [1318] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
    ACTIONS(243), 1,
      aux_sym_quoted_string_token2,
  [1328] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    ACTIONS(245), 1,
      anon_sym_SPACE,
  [1338] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    ACTIONS(247), 1,
      anon_sym_SPACE,
  [1348] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(249), 1,
      sym_path,
    ACTIONS(251), 1,
      sym_name,
  [1358] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(253), 1,
      anon_sym_SPACE,
  [1368] = 3,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(156), 1,
      anon_sym_STAR,
    STATE(72), 1,
      sym_glob,
  [1378] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    ACTIONS(257), 1,
      anon_sym_SPACE,
  [1388] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    ACTIONS(261), 1,
      anon_sym_SPACE,
  [1398] = 3,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
    ACTIONS(265), 1,
      anon_sym_SPACE,
  [1408] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
  [1415] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
  [1422] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(271), 1,
      sym_path,
  [1429] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(267), 1,
      anon_sym_SQUOTE,
  [1436] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(273), 1,
      sym_name,
  [1443] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(275), 1,
      sym_name,
  [1450] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
  [1457] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(279), 1,
      ts_builtin_sym_end,
  [1464] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(281), 1,
      anon_sym_EQ,
  [1471] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(283), 1,
      anon_sym_RBRACK,
  [1478] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
  [1485] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
  [1492] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
  [1499] = 2,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(291), 1,
      anon_sym_SPACE,
  [1506] = 2,
    ACTIONS(3), 1,
      sym__line_continuation,
    ACTIONS(293), 1,
      sym_name,
  [1513] = 2,
    ACTIONS(38), 1,
      sym__line_continuation,
    ACTIONS(295), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 151,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 205,
  [SMALL_STATE(9)] = 229,
  [SMALL_STATE(10)] = 257,
  [SMALL_STATE(11)] = 283,
  [SMALL_STATE(12)] = 311,
  [SMALL_STATE(13)] = 335,
  [SMALL_STATE(14)] = 359,
  [SMALL_STATE(15)] = 388,
  [SMALL_STATE(16)] = 409,
  [SMALL_STATE(17)] = 428,
  [SMALL_STATE(18)] = 447,
  [SMALL_STATE(19)] = 466,
  [SMALL_STATE(20)] = 487,
  [SMALL_STATE(21)] = 506,
  [SMALL_STATE(22)] = 523,
  [SMALL_STATE(23)] = 540,
  [SMALL_STATE(24)] = 557,
  [SMALL_STATE(25)] = 574,
  [SMALL_STATE(26)] = 591,
  [SMALL_STATE(27)] = 608,
  [SMALL_STATE(28)] = 625,
  [SMALL_STATE(29)] = 642,
  [SMALL_STATE(30)] = 659,
  [SMALL_STATE(31)] = 676,
  [SMALL_STATE(32)] = 693,
  [SMALL_STATE(33)] = 721,
  [SMALL_STATE(34)] = 749,
  [SMALL_STATE(35)] = 777,
  [SMALL_STATE(36)] = 805,
  [SMALL_STATE(37)] = 826,
  [SMALL_STATE(38)] = 851,
  [SMALL_STATE(39)] = 876,
  [SMALL_STATE(40)] = 897,
  [SMALL_STATE(41)] = 922,
  [SMALL_STATE(42)] = 944,
  [SMALL_STATE(43)] = 962,
  [SMALL_STATE(44)] = 984,
  [SMALL_STATE(45)] = 1006,
  [SMALL_STATE(46)] = 1024,
  [SMALL_STATE(47)] = 1046,
  [SMALL_STATE(48)] = 1061,
  [SMALL_STATE(49)] = 1073,
  [SMALL_STATE(50)] = 1089,
  [SMALL_STATE(51)] = 1103,
  [SMALL_STATE(52)] = 1115,
  [SMALL_STATE(53)] = 1128,
  [SMALL_STATE(54)] = 1141,
  [SMALL_STATE(55)] = 1154,
  [SMALL_STATE(56)] = 1167,
  [SMALL_STATE(57)] = 1180,
  [SMALL_STATE(58)] = 1193,
  [SMALL_STATE(59)] = 1206,
  [SMALL_STATE(60)] = 1219,
  [SMALL_STATE(61)] = 1232,
  [SMALL_STATE(62)] = 1245,
  [SMALL_STATE(63)] = 1258,
  [SMALL_STATE(64)] = 1271,
  [SMALL_STATE(65)] = 1282,
  [SMALL_STATE(66)] = 1295,
  [SMALL_STATE(67)] = 1308,
  [SMALL_STATE(68)] = 1318,
  [SMALL_STATE(69)] = 1328,
  [SMALL_STATE(70)] = 1338,
  [SMALL_STATE(71)] = 1348,
  [SMALL_STATE(72)] = 1358,
  [SMALL_STATE(73)] = 1368,
  [SMALL_STATE(74)] = 1378,
  [SMALL_STATE(75)] = 1388,
  [SMALL_STATE(76)] = 1398,
  [SMALL_STATE(77)] = 1408,
  [SMALL_STATE(78)] = 1415,
  [SMALL_STATE(79)] = 1422,
  [SMALL_STATE(80)] = 1429,
  [SMALL_STATE(81)] = 1436,
  [SMALL_STATE(82)] = 1443,
  [SMALL_STATE(83)] = 1450,
  [SMALL_STATE(84)] = 1457,
  [SMALL_STATE(85)] = 1464,
  [SMALL_STATE(86)] = 1471,
  [SMALL_STATE(87)] = 1478,
  [SMALL_STATE(88)] = 1485,
  [SMALL_STATE(89)] = 1492,
  [SMALL_STATE(90)] = 1499,
  [SMALL_STATE(91)] = 1506,
  [SMALL_STATE(92)] = 1513,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency, 1, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_dependency, 1, 0, 0), SHIFT(34),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dependency_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dependency_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dependency_repeat1, 2, 0, 0), SHIFT(34),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dependency_repeat1, 2, 0, 0), SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_dependency, 1, 0, 0), SHIFT(32),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_dependency, 2, 0, 0), SHIFT(32),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_dependency, 2, 0, 0), SHIFT(34),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dependency_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_target, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_target, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_target, 4, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_target, 4, 0, 2),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dependency_repeat1, 2, 0, 0), SHIFT(32),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_target, 6, 0, 4),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multi_target, 6, 0, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 5, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 6, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 6, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assigner, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assigner, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subject_repeat3, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat3, 2, 0, 0), SHIFT_REPEAT(73),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subject_repeat2, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat2, 2, 0, 0), SHIFT_REPEAT(49),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subject_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_glob, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_glob, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_attribute, 5, 0, 3),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_target_attribute, 5, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat2, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat3, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subject_repeat2, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat2, 3, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subject_repeat1, 3, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 3, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_glob, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_glob, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [279] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_build2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "build2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
